apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice1
  labels:
    app: microservice1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice1
  template:
    metadata:
      labels:
        app: microservice1
    spec:
      containers:
      - name: microservice1
        image: <your-dockerhub-username>/microservice1:latest
        ports:
        - containerPort: 8000
        env:
        - name: MICROSERVICE_2_URL
          value: "http://microservice2.default.svc.cluster.local:8000"
---
apiVersion: v1
kind: Service
metadata:
  name: microservice1
spec:
  selector:
    app: microservice1
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
